[Unit]
StartLimitIntervalSec=0

[Service]
Restart=always
RestartSec=2
Nice=0
CPUWeight=10000
IOWeight=10000
IOSchedulingClass=best-effort
IOSchedulingPriority=0
MemoryLow=512M
MemoryHigh=12G
MemoryMax=14G
MemorySwapMax=2G
TasksMax=2048
LimitNOFILE=1048576
